Record menu
kageyama0/intern-line-bot pull request #2
Opened 2020-01-29 07:34 UTC by kageyama0

## 実装の背景・目的
・まず、前回のプルリクでいただいた指摘に関する部分は、あらかた直しました。
　変数のスコープ / 「グルメニュース」でも反応する問題
「メニュー」以外の言葉を送信したときに、オウム返しをしていた部分は消して、規定の言葉以外には何も返さないことにしました。ゆくゆくは文字を送信する のではなく、ボタンで全部できるようにするつもりなので...時間があれば...

・今回は、「メニュー」/「やった」もしくは「done」と送信したときの処理を書きました。

## やったこと
「メニュー」
・まず、その日ユーザーが「メニュー」と送信したかどうかは、データベースに保存されてる一番新しい筋トレ記録の日付と現在の日付を比較して判断しています。
(一番初めにこのBotを利用した場合、最新の筋トレ記録がないので、バグような気がします。
のちのち実装します。)

・その日にユーザーが「メニュー」と送信していなかった場合
新しくデータを作成し、作成した筋トレメニューをユーザーに送信します。

・その日にユーザーが「メニュー」と送信していた場合
データベースにあるTrainingテーブルのmenuカラムの中身を書き換えるようにしています。

「やった」or「done」
・その日にユーザーが「メニュー」と送信していなかった場合
「先にメニューを選んでください！」とユーザーにメッセージを送ります。

・その日にユーザーが「メニュー」と送信していなかった場合
「お疲れさまです」とユーザーに送信します。
　※69行目にresponse1 = ""とありますが、消し忘れてました...

## キャプチャ
![Screenshot-dev2](https://user-images.githubusercontent.com/48192683/73334708-c715e680-42b0-11ea-8231-7ff8e1097481.jpg)

※スクショの15:16と15:21の「メニュー」に反応してないのは、herokuにプッシュしたやつがバグってるときにやったものだからです。

2020-01-29 08:34 UTC, yashi8484 reviewed
コードのコメントがとても丁寧ですね・・・！
botがやりたいこと(仕様)を達成するために、どういうアルゴリズムで処理したら良いかを考え、その結果をコードに丁寧に落とし込んでいる様子が見て取れます。(他の人がコードを読んだときに自分が書いたコードの意図を伝えられるという点でもgoodです)

一方で、「コメントを書かなくても分かりやすいようなコードを書く」ことを心がけて見ても良いかもしれません。
コードを分かりやすくするための方法はたくさんあるのですが、一例を挙げますね。
今回「筋トレメニュー」を表す `menu` という変数を定義していますが、これを例えば `muscle_training_menu` という名前にすると、名前を見ただけで「筋トレメニュー」であることが明示されます。
そうすると、 `#筋トレメニュー` とコメントを書かなくても意味が分かるようになりそうですね。

(変数名に限らないのですが、)コードに意味を持たせることを意識すると、もっと分かりやすいコードが書けると思いますので、tryしてみてください！

2020-01-29 08:34 UTC, yashi8484 commented on app/controllers/webhook_controller.rb
> +              response1 = menu.sample
[IMO] `response1` `response2` という名前を、それぞれ変数の名前を見ただけで何が入っているのか分かるような命名にすると、もっと良くなりそうです・・・！

2020-01-29 08:34 UTC, yashi8484 commented on app/controllers/webhook_controller.rb
> +          @today = Date.parse(String(Time.current).split()[0])
Rubyは、今日の日付をとても簡単に取得することができますよ・・・！
https://docs.ruby-lang.org/ja/2.6.0/method/Date/s/today.html

2020-01-29 08:42 UTC, kageyama0 commented on app/controllers/webhook_controller.rb
> +              response1 = menu.sample
response1 --> response_for_menu
response2 --> response_for_done
に変更してみました。

2020-01-29 08:48 UTC, kageyama0 commented on app/controllers/webhook_controller.rb
> +          @today = Date.parse(String(Time.current).split()[0])
Date.todayに変更しました！

2020-01-29 10:46 UTC, megane42 requested changes
一通り確認しましたー

2020-01-29 10:46 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +          @latest_training_date = Date.parse(String(@latest_training.created_at).split()[0])
難しいｗ
`@latest_training_date = @latest_training.created_at` だとまずいんでしたっけ

2020-01-29 10:46 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +          client.push_message(ENV['LINE_GROUP_ID'],message)
この `push_message` って何が起きるんでしたっけ？

1つ上の行で `reply_message` もしてるので、同じメッセージが 2 回届く・・・？

2020-01-29 10:46 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +          @latest_training = Training.find_by(id: Training.count)
アットマークで始まる変数は Ruby (や Rails のコントローラ）では特別な意味があって、詳しくは割愛しますが、今の使い方であればどれもアットマークは必要ないかなと思います。

```ruby
latest_training = Training.find_by(id: Training.count)
```

2020-01-29 10:46 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +          @latest_training = Training.find_by(id: Training.count)
> `find_by(id: Training.count)`

これですが、id カラムは歯抜けになることがありうる（例えばレコードを消したときとか）ので、  このコードで常に最新レコードが得られるとは限りません。あと単純にコードとしてもあまり直感的じゃないかも・・・？と思いました。

Training を created_at 順に並べ替えて最新の 1 件だけを取る、というふうにすると確実だと思います。

2020-01-29 10:46 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +            if event.message['text'] == "メニュー"
`event.message['text']` を解析して "メニュー" か "やった" か判断する処理がちょくちょくあるので、それぞれ `message_for_menu?` `message_for_done?` みたいなメソッドにして、それを各所で使うようにするのはどうでしょう？（このネーミングがいいかはさておき）

2020-01-29 10:46 UTC, megane42 commented on db/migrate/20200128061656_create_trainings.rb
> +      t.boolean :check, default: false
`check` だと何を指すのかちょっと曖昧だと思うので、 `done` とか `complete` とか `finish` とかだとより具体的かな？と思いました。

ちなみに Rails で boolean のカラムを作ると、例えばカラム名が `done` なら `done?` というメソッドが自動的に生えます。直感的にわかるとおり、done カラムが true なら true を返すようなメソッドです。
https://teratail.com/questions/40723

2020-01-29 11:53 UTC, kageyama0 commented on app/controllers/webhook_controller.rb
> +          client.push_message(ENV['LINE_GROUP_ID'],message)
push_messageは、LINEグループの方にメッセージを送るやつです！
LINEグループにメッセージを送れるか確認するために、一旦ここに書いていたやつを消し忘れていました。すみません！

2020-01-29 11:55 UTC, kageyama0 commented on app/controllers/webhook_controller.rb
> +          @latest_training_date = Date.parse(String(@latest_training.created_at).split()[0])
日にちだけ比較したかったので、こう書きました。
.created_atだと、時間も入っちゃうんです。

2020-01-30 00:37 UTC, kageyama0 commented on db/migrate/20200128061656_create_trainings.rb
> +      t.boolean :check, default: false
カラム名をcheck --> done に変更しました。

2020-01-30 00:39 UTC, kageyama0 commented on app/controllers/webhook_controller.rb
> +            if event.message['text'] == "メニュー"
event.message['text'] --> received_msg = event.message['text'] と定義しておきました。
message_for_menu? message_for_done?メソッドを作成しました。

2020-01-30 00:40 UTC, kageyama0 commented on app/controllers/webhook_controller.rb
> +          @latest_training = Training.find_by(id: Training.count)
latest_training = Training.order('created_at DESC').first
こんな感じでしょうか？

2020-01-30 01:31 UTC, HiroyukiNakatsuma reviewed
@kageyama0 一旦コメントしましたー！！

2020-01-30 01:31 UTC, HiroyukiNakatsuma commented on app/controllers/webhook_controller.rb
> +      config.channel_token = "huLMDPpMa+A/GT0/WJZNA3lZvDjOBhYjIxSRzehEmiTZm74esUoRzg0R+ug/A1C7NwuGTpJpOozlribUhYXv40LjEPRw1+Vd23qwADllzWyhezcTtJ7kGADZcbLz4WUvMuxS8wDediB1bLm8GFv36QdB04t89/1O/w1cDnyil
@kageyama0 [MUST] 認証情報は git に commit するのは NG です.. (業務での本格的なコーディング経験がないので仕方ないですが)

元々の `config.channel_secret = ENV["LINE_CHANNEL_SECRET"]` では環境変数 `$LINE_CHANNEL_SECRET` から値を取得しているので、その方法でお願いしたいです🙏

2020-01-30 01:32 UTC, kageyama0 commented on app/controllers/webhook_controller.rb
> +      config.channel_token = "huLMDPpMa+A/GT0/WJZNA3lZvDjOBhYjIxSRzehEmiTZm74esUoRzg0R+ug/A1C7NwuGTpJpOozlribUhYXv40LjEPRw1+Vd23qwADllzWyhezcTtJ7kGADZcbLz4WUvMuxS8wDediB1bLm8GFv36QdB04t89/1O/w1cDnyil
ngrokで検証するために、一旦直接書き込んだやつを消し忘れていました！

2020-01-30 02:17 UTC, megane42 requested changes
さらにコメントしましたー

2020-01-30 02:17 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +    if msg == "メニュー"
[nits] ruby は関数内の最後の評価値が暗黙的にそのまま return されるので、 ↓ のように書けたりします

```ruby
def  message_for_menu?(msg)
  msg == "メニュー"
end
```

2020-01-30 02:17 UTC, megane42 commented on db/migrate/20200128061656_create_trainings.rb
> +      t.boolean :check, default: false
👍

2020-01-30 02:17 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +          latest_training_date = Date.parse(String(latest_training.created_at).split()[0])
なるほどです！
とはいえちょっと可読性が低いかなと思ったので、色々実験してみたら、↓ でいけてしまいました。

```ruby
latest_training_date = Date.parse(latest_training.created_at.to_s)
```

で、さらに調べたら `today?` という神メソッドを見つけたので、これを使うといいかもです（これならそもそも `latest_training_date` が要らなくなる）。
https://api.rubyonrails.org/v6.0.2.1/classes/ActiveSupport/TimeWithZone.html#method-i-today-3F

```ruby
latest_training.created_at.today?
# => true or false
```

2020-01-30 02:18 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +          client.push_message(ENV['LINE_GROUP_ID'],message)
:+1:

2020-01-30 02:19 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +          @latest_training = Training.find_by(id: Training.count)
👍 
`order(...)` のあとに `.limit(1)` を付けるとさらに効率的になるかも。

2020-01-30 02:19 UTC, megane42 commented on app/controllers/webhook_controller.rb
> +            if event.message['text'] == "メニュー"
👍

2020-01-30 02:34 UTC, merged